### ISSUE TITLE
ETA in w8m8

### ISSUE THREAD

**Issue by sorsater** [Lufftre/w8m8#2]
I try to use w8m8 in my thesis.
However, I need functionality to use ETA in the progressbar.
Is it possible in the current version?

Regards
Devoted waiting mate

**Comment by Lufftre** [comment]
Hi Mr. sorsater,

The functionality you are describing is in our backlog and we will see it added some time in the future.
However I can not give you an ETA so you just have to w8m8 😎😎😎😎

**Comment by Lufftre** [comment]
Hi mr m8,
Please update your package 😃
